### ISSUE TITLE
Not obvious where to save the files

### ISSUE THREAD

**Issue by monk-e-boy** [unovafr/Godot-Orbit-Camera#6]
Add a step in the readme.md that describes where to save the folders and files (in your project folder)

**Comment by monk-e-boy** [comment]
![image](https://user-images.githubusercontent.com/17924807/86532787-67a5ad80-bec4-11ea-8f79-d5458d0a070f.png)

**Comment by monk-e-boy** [comment]
Sorry, just testing that pasting a screenshot works :)

![image](https://user-images.githubusercontent.com/17924807/86532804-89069980-bec4-11ea-95fa-44262658f447.png)

**Comment by monk-e-boy** [comment]
I hope those screenshots can be used in the docs :) I like this plugin - it rocks!

**Comment by mrdev023** [comment]
It's closed?
@monk-e-boy
