### ISSUE TITLE
Compatibility with Godot 4.0?

### ISSUE THREAD

**Issue by ThePortuguesePlayer** [unovafr/Godot-Orbit-Camera#7]
I don't know of this addon is still getting maintained, but, just in case it is...
I converted one of my projects that was using this addon from Godot 3.5.1 to 4.0. Everything with the addon seems to be working right except the mouse rotation. The actual orbiting part. Zoom works fine. I am not being quite able to figure out why the rotation stopped working, as all functions and classes seem to have been converted correctly...
Have you tried it on Godot 4.0?

**Comment by mrdev023** [comment]
@ThePortuguesePlayer I check that. Sorry for the late reply
